version: "3.7"

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        platform : 'linux/x86_64'
        volumes:
            - todo-mysql-data:/Applications/XAMPP/xamppfiles/var/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3307:3306"
        networks:
            - sql_network
        environment:
            - MYSQL_DATABASE=projecttest
            - MYSQL_ROOT_PASSWORD=root
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        command: "php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - mysql
        networks:
            - sql_network
        env_file:
            - .env
networks:
    sql_network:
        external: false
        name: sql_network

volumes:
    todo-mysql-data:
        external: false
